name: 'Init Config Files'
description: 'GitHub Action que crea archivos de configuraci칩n inicial si no existen'
inputs:
  TOKEN:
    description: 'Token para hacer commit y push. Se recomienda usar el GITHUB_TOKEN de GitHub'
    required: true
  BRANCH:
    description: 'Nombre de la rama a la que se har치 push. Si no se especifica, se usar치 la rama actual del workflow.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Crear archivos de configuraci칩n
      env:
        VAR_TOKEN: ${{ inputs.TOKEN }}
        VAR_BRANCH: ${{ inputs.BRANCH }}
      shell: bash
      run: ./scripts/create_md_files.sh
    - name: Setup Node.js
      env:
        GH_TOKEN: ${{ inputs.TOKEN }}
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - name: Install Semantic-Release
      env:
        VAR_NAME_REPOSITORY: ${{ github.repository }}
      run: ./scripts/install_semantic_release.sh
      shell: bash
